# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _MGSimCore
else:
    import _MGSimCore

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _MGSimCore.delete_SwigPyIterator

    def value(self):
        return _MGSimCore.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _MGSimCore.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _MGSimCore.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _MGSimCore.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _MGSimCore.SwigPyIterator_equal(self, x)

    def copy(self):
        return _MGSimCore.SwigPyIterator_copy(self)

    def next(self):
        return _MGSimCore.SwigPyIterator_next(self)

    def __next__(self):
        return _MGSimCore.SwigPyIterator___next__(self)

    def previous(self):
        return _MGSimCore.SwigPyIterator_previous(self)

    def advance(self, n):
        return _MGSimCore.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _MGSimCore.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _MGSimCore.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _MGSimCore.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _MGSimCore.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _MGSimCore.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _MGSimCore.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _MGSimCore:
_MGSimCore.SwigPyIterator_swigregister(SwigPyIterator)

class IntVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _MGSimCore.IntVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _MGSimCore.IntVector___nonzero__(self)

    def __bool__(self):
        return _MGSimCore.IntVector___bool__(self)

    def __len__(self):
        return _MGSimCore.IntVector___len__(self)

    def __getslice__(self, i, j):
        return _MGSimCore.IntVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _MGSimCore.IntVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _MGSimCore.IntVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _MGSimCore.IntVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _MGSimCore.IntVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _MGSimCore.IntVector___setitem__(self, *args)

    def pop(self):
        return _MGSimCore.IntVector_pop(self)

    def append(self, x):
        return _MGSimCore.IntVector_append(self, x)

    def empty(self):
        return _MGSimCore.IntVector_empty(self)

    def size(self):
        return _MGSimCore.IntVector_size(self)

    def swap(self, v):
        return _MGSimCore.IntVector_swap(self, v)

    def begin(self):
        return _MGSimCore.IntVector_begin(self)

    def end(self):
        return _MGSimCore.IntVector_end(self)

    def rbegin(self):
        return _MGSimCore.IntVector_rbegin(self)

    def rend(self):
        return _MGSimCore.IntVector_rend(self)

    def clear(self):
        return _MGSimCore.IntVector_clear(self)

    def get_allocator(self):
        return _MGSimCore.IntVector_get_allocator(self)

    def pop_back(self):
        return _MGSimCore.IntVector_pop_back(self)

    def erase(self, *args):
        return _MGSimCore.IntVector_erase(self, *args)

    def __init__(self, *args):
        _MGSimCore.IntVector_swiginit(self, _MGSimCore.new_IntVector(*args))

    def push_back(self, x):
        return _MGSimCore.IntVector_push_back(self, x)

    def front(self):
        return _MGSimCore.IntVector_front(self)

    def back(self):
        return _MGSimCore.IntVector_back(self)

    def assign(self, n, x):
        return _MGSimCore.IntVector_assign(self, n, x)

    def resize(self, *args):
        return _MGSimCore.IntVector_resize(self, *args)

    def insert(self, *args):
        return _MGSimCore.IntVector_insert(self, *args)

    def reserve(self, n):
        return _MGSimCore.IntVector_reserve(self, n)

    def capacity(self):
        return _MGSimCore.IntVector_capacity(self)
    __swig_destroy__ = _MGSimCore.delete_IntVector

# Register IntVector in _MGSimCore:
_MGSimCore.IntVector_swigregister(IntVector)

class DoubleVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _MGSimCore.DoubleVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _MGSimCore.DoubleVector___nonzero__(self)

    def __bool__(self):
        return _MGSimCore.DoubleVector___bool__(self)

    def __len__(self):
        return _MGSimCore.DoubleVector___len__(self)

    def __getslice__(self, i, j):
        return _MGSimCore.DoubleVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _MGSimCore.DoubleVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _MGSimCore.DoubleVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _MGSimCore.DoubleVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _MGSimCore.DoubleVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _MGSimCore.DoubleVector___setitem__(self, *args)

    def pop(self):
        return _MGSimCore.DoubleVector_pop(self)

    def append(self, x):
        return _MGSimCore.DoubleVector_append(self, x)

    def empty(self):
        return _MGSimCore.DoubleVector_empty(self)

    def size(self):
        return _MGSimCore.DoubleVector_size(self)

    def swap(self, v):
        return _MGSimCore.DoubleVector_swap(self, v)

    def begin(self):
        return _MGSimCore.DoubleVector_begin(self)

    def end(self):
        return _MGSimCore.DoubleVector_end(self)

    def rbegin(self):
        return _MGSimCore.DoubleVector_rbegin(self)

    def rend(self):
        return _MGSimCore.DoubleVector_rend(self)

    def clear(self):
        return _MGSimCore.DoubleVector_clear(self)

    def get_allocator(self):
        return _MGSimCore.DoubleVector_get_allocator(self)

    def pop_back(self):
        return _MGSimCore.DoubleVector_pop_back(self)

    def erase(self, *args):
        return _MGSimCore.DoubleVector_erase(self, *args)

    def __init__(self, *args):
        _MGSimCore.DoubleVector_swiginit(self, _MGSimCore.new_DoubleVector(*args))

    def push_back(self, x):
        return _MGSimCore.DoubleVector_push_back(self, x)

    def front(self):
        return _MGSimCore.DoubleVector_front(self)

    def back(self):
        return _MGSimCore.DoubleVector_back(self)

    def assign(self, n, x):
        return _MGSimCore.DoubleVector_assign(self, n, x)

    def resize(self, *args):
        return _MGSimCore.DoubleVector_resize(self, *args)

    def insert(self, *args):
        return _MGSimCore.DoubleVector_insert(self, *args)

    def reserve(self, n):
        return _MGSimCore.DoubleVector_reserve(self, n)

    def capacity(self):
        return _MGSimCore.DoubleVector_capacity(self)
    __swig_destroy__ = _MGSimCore.delete_DoubleVector

# Register DoubleVector in _MGSimCore:
_MGSimCore.DoubleVector_swigregister(DoubleVector)

class StringVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _MGSimCore.StringVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _MGSimCore.StringVector___nonzero__(self)

    def __bool__(self):
        return _MGSimCore.StringVector___bool__(self)

    def __len__(self):
        return _MGSimCore.StringVector___len__(self)

    def __getslice__(self, i, j):
        return _MGSimCore.StringVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _MGSimCore.StringVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _MGSimCore.StringVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _MGSimCore.StringVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _MGSimCore.StringVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _MGSimCore.StringVector___setitem__(self, *args)

    def pop(self):
        return _MGSimCore.StringVector_pop(self)

    def append(self, x):
        return _MGSimCore.StringVector_append(self, x)

    def empty(self):
        return _MGSimCore.StringVector_empty(self)

    def size(self):
        return _MGSimCore.StringVector_size(self)

    def swap(self, v):
        return _MGSimCore.StringVector_swap(self, v)

    def begin(self):
        return _MGSimCore.StringVector_begin(self)

    def end(self):
        return _MGSimCore.StringVector_end(self)

    def rbegin(self):
        return _MGSimCore.StringVector_rbegin(self)

    def rend(self):
        return _MGSimCore.StringVector_rend(self)

    def clear(self):
        return _MGSimCore.StringVector_clear(self)

    def get_allocator(self):
        return _MGSimCore.StringVector_get_allocator(self)

    def pop_back(self):
        return _MGSimCore.StringVector_pop_back(self)

    def erase(self, *args):
        return _MGSimCore.StringVector_erase(self, *args)

    def __init__(self, *args):
        _MGSimCore.StringVector_swiginit(self, _MGSimCore.new_StringVector(*args))

    def push_back(self, x):
        return _MGSimCore.StringVector_push_back(self, x)

    def front(self):
        return _MGSimCore.StringVector_front(self)

    def back(self):
        return _MGSimCore.StringVector_back(self)

    def assign(self, n, x):
        return _MGSimCore.StringVector_assign(self, n, x)

    def resize(self, *args):
        return _MGSimCore.StringVector_resize(self, *args)

    def insert(self, *args):
        return _MGSimCore.StringVector_insert(self, *args)

    def reserve(self, n):
        return _MGSimCore.StringVector_reserve(self, n)

    def capacity(self):
        return _MGSimCore.StringVector_capacity(self)
    __swig_destroy__ = _MGSimCore.delete_StringVector

# Register StringVector in _MGSimCore:
_MGSimCore.StringVector_swigregister(StringVector)

class ConstCharVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _MGSimCore.ConstCharVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _MGSimCore.ConstCharVector___nonzero__(self)

    def __bool__(self):
        return _MGSimCore.ConstCharVector___bool__(self)

    def __len__(self):
        return _MGSimCore.ConstCharVector___len__(self)

    def __getslice__(self, i, j):
        return _MGSimCore.ConstCharVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _MGSimCore.ConstCharVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _MGSimCore.ConstCharVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _MGSimCore.ConstCharVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _MGSimCore.ConstCharVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _MGSimCore.ConstCharVector___setitem__(self, *args)

    def pop(self):
        return _MGSimCore.ConstCharVector_pop(self)

    def append(self, x):
        return _MGSimCore.ConstCharVector_append(self, x)

    def empty(self):
        return _MGSimCore.ConstCharVector_empty(self)

    def size(self):
        return _MGSimCore.ConstCharVector_size(self)

    def swap(self, v):
        return _MGSimCore.ConstCharVector_swap(self, v)

    def begin(self):
        return _MGSimCore.ConstCharVector_begin(self)

    def end(self):
        return _MGSimCore.ConstCharVector_end(self)

    def rbegin(self):
        return _MGSimCore.ConstCharVector_rbegin(self)

    def rend(self):
        return _MGSimCore.ConstCharVector_rend(self)

    def clear(self):
        return _MGSimCore.ConstCharVector_clear(self)

    def get_allocator(self):
        return _MGSimCore.ConstCharVector_get_allocator(self)

    def pop_back(self):
        return _MGSimCore.ConstCharVector_pop_back(self)

    def erase(self, *args):
        return _MGSimCore.ConstCharVector_erase(self, *args)

    def __init__(self, *args):
        _MGSimCore.ConstCharVector_swiginit(self, _MGSimCore.new_ConstCharVector(*args))

    def push_back(self, x):
        return _MGSimCore.ConstCharVector_push_back(self, x)

    def front(self):
        return _MGSimCore.ConstCharVector_front(self)

    def back(self):
        return _MGSimCore.ConstCharVector_back(self)

    def assign(self, n, x):
        return _MGSimCore.ConstCharVector_assign(self, n, x)

    def resize(self, *args):
        return _MGSimCore.ConstCharVector_resize(self, *args)

    def insert(self, *args):
        return _MGSimCore.ConstCharVector_insert(self, *args)

    def reserve(self, n):
        return _MGSimCore.ConstCharVector_reserve(self, n)

    def capacity(self):
        return _MGSimCore.ConstCharVector_capacity(self)
    __swig_destroy__ = _MGSimCore.delete_ConstCharVector

# Register ConstCharVector in _MGSimCore:
_MGSimCore.ConstCharVector_swigregister(ConstCharVector)

class cMGSimCore(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, enable_draw):
        _MGSimCore.cMGSimCore_swiginit(self, _MGSimCore.new_cMGSimCore(enable_draw))
    __swig_destroy__ = _MGSimCore.delete_cMGSimCore

    def SeedRand(self, seed):
        return _MGSimCore.cMGSimCore_SeedRand(self, seed)

    def ParseArgs(self, args):
        return _MGSimCore.cMGSimCore_ParseArgs(self, args)

    def Init(self):
        return _MGSimCore.cMGSimCore_Init(self)

    def Update(self, timestep):
        return _MGSimCore.cMGSimCore_Update(self, timestep)

    def Reset(self):
        return _MGSimCore.cMGSimCore_Reset(self)

    def GetTime(self):
        return _MGSimCore.cMGSimCore_GetTime(self)

    def GetName(self):
        return _MGSimCore.cMGSimCore_GetName(self)

    def EnableDraw(self):
        return _MGSimCore.cMGSimCore_EnableDraw(self)

    def Draw(self):
        return _MGSimCore.cMGSimCore_Draw(self)

    def Keyboard(self, key, x, y):
        return _MGSimCore.cMGSimCore_Keyboard(self, key, x, y)

    def MouseClick(self, button, state, x, y):
        return _MGSimCore.cMGSimCore_MouseClick(self, button, state, x, y)

    def MouseMove(self, x, y):
        return _MGSimCore.cMGSimCore_MouseMove(self, x, y)

    def Reshape(self, w, h):
        return _MGSimCore.cMGSimCore_Reshape(self, w, h)

    def Shutdown(self):
        return _MGSimCore.cMGSimCore_Shutdown(self)

    def IsDone(self):
        return _MGSimCore.cMGSimCore_IsDone(self)

    def GetDrawScene(self):
        return _MGSimCore.cMGSimCore_GetDrawScene(self)

    def SetPlaybackSpeed(self, speed):
        return _MGSimCore.cMGSimCore_SetPlaybackSpeed(self, speed)

    def SetUpdatesPerSec(self, updates_per_sec):
        return _MGSimCore.cMGSimCore_SetUpdatesPerSec(self, updates_per_sec)

    def GetWinWidth(self):
        return _MGSimCore.cMGSimCore_GetWinWidth(self)

    def GetWinHeight(self):
        return _MGSimCore.cMGSimCore_GetWinHeight(self)

    def GetNumUpdateSubsteps(self):
        return _MGSimCore.cMGSimCore_GetNumUpdateSubsteps(self)

    def IsRLScene(self):
        return _MGSimCore.cMGSimCore_IsRLScene(self)

    def GetNumAgents(self):
        return _MGSimCore.cMGSimCore_GetNumAgents(self)

    def NeedNewAction(self, agent_id):
        return _MGSimCore.cMGSimCore_NeedNewAction(self, agent_id)

    def RecordState(self, agent_id):
        return _MGSimCore.cMGSimCore_RecordState(self, agent_id)

    def RecordGoal(self, agent_id):
        return _MGSimCore.cMGSimCore_RecordGoal(self, agent_id)

    def SetAction(self, agent_id, action):
        return _MGSimCore.cMGSimCore_SetAction(self, agent_id, action)

    def LogVal(self, agent_id, val):
        return _MGSimCore.cMGSimCore_LogVal(self, agent_id, val)

    def GetActionSpace(self, agent_id):
        return _MGSimCore.cMGSimCore_GetActionSpace(self, agent_id)

    def GetStateSize(self, agent_id):
        return _MGSimCore.cMGSimCore_GetStateSize(self, agent_id)

    def GetGoalSize(self, agent_id):
        return _MGSimCore.cMGSimCore_GetGoalSize(self, agent_id)

    def GetActionSize(self, agent_id):
        return _MGSimCore.cMGSimCore_GetActionSize(self, agent_id)

    def GetNumActions(self, agent_id):
        return _MGSimCore.cMGSimCore_GetNumActions(self, agent_id)

    def BuildStateOffset(self, agent_id):
        return _MGSimCore.cMGSimCore_BuildStateOffset(self, agent_id)

    def BuildStateScale(self, agent_id):
        return _MGSimCore.cMGSimCore_BuildStateScale(self, agent_id)

    def BuildGoalOffset(self, agent_id):
        return _MGSimCore.cMGSimCore_BuildGoalOffset(self, agent_id)

    def BuildGoalScale(self, agent_id):
        return _MGSimCore.cMGSimCore_BuildGoalScale(self, agent_id)

    def BuildActionOffset(self, agent_id):
        return _MGSimCore.cMGSimCore_BuildActionOffset(self, agent_id)

    def BuildActionScale(self, agent_id):
        return _MGSimCore.cMGSimCore_BuildActionScale(self, agent_id)

    def BuildActionBoundMin(self, agent_id):
        return _MGSimCore.cMGSimCore_BuildActionBoundMin(self, agent_id)

    def BuildActionBoundMax(self, agent_id):
        return _MGSimCore.cMGSimCore_BuildActionBoundMax(self, agent_id)

    def BuildStateNormGroups(self, agent_id):
        return _MGSimCore.cMGSimCore_BuildStateNormGroups(self, agent_id)

    def BuildGoalNormGroups(self, agent_id):
        return _MGSimCore.cMGSimCore_BuildGoalNormGroups(self, agent_id)

    def CalcReward(self, agent_id):
        return _MGSimCore.cMGSimCore_CalcReward(self, agent_id)

    def GetRewardMin(self, agent_id):
        return _MGSimCore.cMGSimCore_GetRewardMin(self, agent_id)

    def GetRewardMax(self, agent_id):
        return _MGSimCore.cMGSimCore_GetRewardMax(self, agent_id)

    def GetRewardFail(self, agent_id):
        return _MGSimCore.cMGSimCore_GetRewardFail(self, agent_id)

    def GetRewardSucc(self, agent_id):
        return _MGSimCore.cMGSimCore_GetRewardSucc(self, agent_id)

    def IsEpisodeEnd(self):
        return _MGSimCore.cMGSimCore_IsEpisodeEnd(self)

    def CheckValidEpisode(self):
        return _MGSimCore.cMGSimCore_CheckValidEpisode(self)

    def CheckTerminate(self, agent_id):
        return _MGSimCore.cMGSimCore_CheckTerminate(self, agent_id)

    def SetMode(self, mode):
        return _MGSimCore.cMGSimCore_SetMode(self, mode)

    def SetSampleCount(self, count):
        return _MGSimCore.cMGSimCore_SetSampleCount(self, count)

# Register cMGSimCore in _MGSimCore:
_MGSimCore.cMGSimCore_swigregister(cMGSimCore)



